INSERT INTO USER_ROLES (USER_ROLES_ID,ROLE_NAME)
	VALUES (1,'ROLE_ADMIN');
INSERT INTO USER_ROLES (USER_ROLES_ID,ROLE_NAME)
	VALUES (2,'ROLE_USER');
INSERT INTO USER_ROLES (USER_ROLES_ID,ROLE_NAME)
	VALUES (3,'ROLE_PATNER');
